'use client'

import React, { useState } from 'react'
import { useUserData } from '../context/UserDataContext'
import { parseJSONL, normaliseEvents, type NormalisedEvent } from '@/services/ra/parser'
import ImportIdeasTab from './ImportIdeasTab'

const SAMPLE_EVENT_COUNT = 4
const MAX_LINEUP_PREVIEW = 3

type ImportPreview = {
  events: Record<string, NormalisedEvent>
  skipped: number
  alreadyPresent: number
  lineupCount: number
}

export default function RAImport() {
  const { batchImportRA } = useUserData()
  const [files, setFiles] = useState<{ events: File | null; lineups: File | null }>({ events: null, lineups: null })
  const [status, setStatus] = useState<{ type: string; message: string }>({ type: '', message: '' })
  const [loading, setLoading] = useState(false)
  const [preview, setPreview] = useState<ImportPreview | null>(null)
  const [tab, setTab] = useState('ra')

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>, type: 'events' | 'lineups') => {
    const file = e.target.files?.[0]
    if (file) {
      setFiles(prev => ({ ...prev, [type]: file }))
      setPreview(null)
      setStatus({ type: '', message: '' })
    }
  }

  const handleParse = async () => {
    if (!files.events) {
      setStatus({ type: 'error', message: 'Please select at least the EventItem.jsonl file.' })
      return
    }
    setLoading(true)
    setStatus({ type: '', message: '' })
    try {
      const eventData = await parseJSONL(files.events)
      const lineupData = files.lineups ? await parseJSONL(files.lineups) : []
      const { events, skipped } = normaliseEvents(eventData, lineupData)
      setPreview({ events, skipped, alreadyPresent: 0, lineupCount: lineupData.length })
    } catch (err) {
      console.error('Parse failed:', err)
      setStatus({ type: 'error', message: 'Failed to parse files. Ensure they are valid JSONL.' })
    } finally {
      setLoading(false)
    }
  }

  const handleImport = () => {
    if (!preview) return
    batchImportRA(preview.events)
    const eventCount = Object.keys(preview.events).length
    const newCount = eventCount - preview.alreadyPresent
    setStatus({
      type: 'success',
      message: `Imported ${eventCount} events (${newCount} new, ${preview.alreadyPresent} updated). They're now searchable on the Discover page!`,
    })
    setPreview(null)
    setFiles({ events: null, lineups: null })
  }

  const resetPreview = () => {
    setPreview(null)
    setStatus({ type: '', message: '' })
  }

  return (
    <div className="import-section fade-in">
      <div style={{ display: 'flex', gap: 0, marginBottom: 24, borderBottom: '1px solid var(--border)' }}>
        {[
          { key: 'ra', label: '📦  Import RA Data' },
          { key: 'ideas', label: '💡  More Ways to Import' },
        ].map(t => (
          <button
            key={t.key}
            className="btn-ghost"
            style={{
              padding: '10px 18px',
              fontWeight: tab === t.key ? 700 : 400,
              borderBottom: tab === t.key ? '2px solid var(--accent)' : '2px solid transparent',
              borderRadius: 0,
              color: tab === t.key ? 'var(--text-primary)' : 'var(--text-secondary)',
              fontSize: '0.88rem',
            }}
            onClick={() => setTab(t.key)}
          >
            {t.label}
          </button>
        ))}
      </div>

      {tab === 'ra' && (
        <RATab
          files={files}
          loading={loading}
          preview={preview}
          status={status}
          onFileChange={handleFileChange}
          onParse={handleParse}
          onImport={handleImport}
          onReset={resetPreview}
        />
      )}

      {tab === 'ideas' && <ImportIdeasTab />}
    </div>
  )
}

function RATab({
  files,
  loading,
  preview,
  status,
  onFileChange,
  onParse,
  onImport,
  onReset,
}: {
  files: { events: File | null; lineups: File | null }
  loading: boolean
  preview: ImportPreview | null
  status: { type: string; message: string }
  onFileChange: (e: React.ChangeEvent<HTMLInputElement>, type: 'events' | 'lineups') => void
  onParse: () => void
  onImport: () => void
  onReset: () => void
}) {
  return (
    <>
      <p style={{ fontSize: '0.9rem', color: 'var(--text-secondary)', marginBottom: 24 }}>
        Upload the <code>.jsonl</code> files generated by <code>ra-scraper</code> to expand your event database.
        Or use the seed script in <code>scripts/seed-ra-events.js</code> to bake them in permanently.
      </p>

      {!preview && (
        <>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16, marginBottom: 20 }}>
            <FileDropzone
              icon="📄"
              label={files.events ? files.events.name : 'EventItem.jsonl'}
              hint="(Required)"
              isActive={!!files.events}
              onChange={e => onFileChange(e, 'events')}
            />
            <FileDropzone
              icon="👥"
              label={files.lineups ? files.lineups.name : 'EventLineupItem.jsonl'}
              hint="(Optional)"
              isActive={!!files.lineups}
              onChange={e => onFileChange(e, 'lineups')}
            />
          </div>

          <button
            className="btn btn-primary"
            onClick={onParse}
            disabled={loading || !files.events}
            style={{ width: '100%' }}
            id="parse-ra-btn"
          >
            {loading ? 'Parsing…' : 'Preview Import'}
          </button>
        </>
      )}

      {preview && (
        <PreviewCard preview={preview} onImport={onImport} onReset={onReset} />
      )}

      {status.message && (
        <div className={`import-status ${status.type}`} style={{ marginTop: 12 }}>
          {status.type === 'success' ? '✅' : '❌'} {status.message}
        </div>
      )}

      <div className="import-instructions" style={{ marginTop: 20 }}>
        <strong>Two ways to import:</strong>
        <ol style={{ paddingLeft: 20, marginTop: 8 }}>
          <li>
            <strong>Browser (above):</strong> select your <code>.jsonl</code> files → preview → confirm. Events are saved in your browser and searchable immediately.
          </li>
          <li>
            <strong>Seed script (permanent):</strong> bakes events permanently into the app so they load for everyone:
            <pre style={{ background: 'var(--bg-surface)', borderRadius: 6, padding: '10px 14px', marginTop: 8, fontSize: '0.78rem', overflowX: 'auto', color: 'var(--text-secondary)' }}>
{`node scripts/seed-ra-events.js \\
  --events "path/to/EventItem.jsonl" \\
  --lineups "path/to/EventLineupItem.jsonl"`}
            </pre>
          </li>
        </ol>
      </div>
    </>
  )
}

function FileDropzone({
  icon,
  label,
  hint,
  isActive,
  onChange,
}: {
  icon: string
  label: string
  hint: string
  isActive: boolean
  onChange: (e: React.ChangeEvent<HTMLInputElement>) => void
}) {
  return (
    <div className={`import-dropzone ${isActive ? 'active' : ''}`} style={{ padding: '20px 10px' }}>
      <label style={{ cursor: 'pointer', display: 'block' }}>
        <div style={{ fontSize: '1.5rem', marginBottom: 8 }}>{icon}</div>
        <div style={{ fontWeight: 600, fontSize: '0.85rem' }}>{label}</div>
        <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>{hint}</div>
        <input type="file" accept=".jsonl,.json" onChange={onChange} style={{ display: 'none' }} />
      </label>
    </div>
  )
}

function PreviewCard({
  preview,
  onImport,
  onReset,
}: {
  preview: ImportPreview
  onImport: () => void
  onReset: () => void
}) {
  const eventCount = Object.keys(preview.events).length
  const stats = [
    { label: 'Events found', value: eventCount, color: 'var(--accent)' },
    { label: 'Already in app', value: preview.alreadyPresent, color: '#fbbf24' },
    { label: 'Artists parsed', value: preview.lineupCount, color: '#34d399' },
  ]

  return (
    <div style={{
      background: 'var(--bg-card)',
      border: '1px solid var(--border-hover)',
      borderRadius: 12,
      padding: '20px 24px',
      marginBottom: 16,
    }}>
      <div style={{ fontFamily: 'var(--font-display)', fontWeight: 700, fontSize: '1.1rem', marginBottom: 16 }}>
        📊 Import Preview
      </div>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 12, marginBottom: 20 }}>
        {stats.map(s => (
          <div key={s.label} style={{ textAlign: 'center', padding: '12px 8px', background: 'var(--bg-surface)', borderRadius: 8 }}>
            <div style={{ fontFamily: 'var(--font-display)', fontWeight: 800, fontSize: '1.6rem', color: s.color }}>{s.value}</div>
            <div style={{ fontSize: '0.72rem', color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>{s.label}</div>
          </div>
        ))}
      </div>

      <div style={{ marginBottom: 16 }}>
        <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)', marginBottom: 8 }}>Sample events:</div>
        {Object.values(preview.events).slice(0, SAMPLE_EVENT_COUNT).map((ev: any) => (
          <div key={ev.id} style={{ fontSize: '0.82rem', padding: '6px 0', borderBottom: '1px solid var(--border)', display: 'flex', gap: 8, alignItems: 'center' }}>
            <span style={{ fontWeight: 600 }}>{ev.name}</span>
            {ev.date && <span style={{ color: 'var(--text-muted)' }}>· {ev.date}</span>}
            {ev.venue?.city && <span style={{ color: 'var(--text-muted)' }}>· {ev.venue.city}</span>}
            {ev.lineup.length > 0 && (
              <span style={{ color: 'var(--text-secondary)', fontSize: '0.75rem' }}>
                ({ev.lineup.slice(0, MAX_LINEUP_PREVIEW).join(', ')}{ev.lineup.length > MAX_LINEUP_PREVIEW ? ` +${ev.lineup.length - MAX_LINEUP_PREVIEW}` : ''})
              </span>
            )}
          </div>
        ))}
      </div>

      <div style={{ display: 'flex', gap: 10 }}>
        <button className="btn btn-primary" onClick={onImport} style={{ flex: 1 }} id="confirm-ra-import-btn">
          Confirm Import
        </button>
        <button className="btn btn-secondary" onClick={onReset} id="cancel-ra-import-btn">
          Cancel
        </button>
      </div>
    </div>
  )
}
